### ISSUE TITLE
word links should maybe use ciw rather than ciW

### ISSUE THREAD

**Issue by ds26gte** [ratfactor/vviki#1]
`ciW` (line 55 in `plugin/vviki.vim`) picks up punctuation, so it's probably better to restrict word links to what can be picked up with `ciw`.  E.g., in the sentence
```
For more details see Note42, Note43, and Note44.
```
if the cursor is on any of the Notes, we wouldn't want to pick up the commas and the period.

(This is not a restriction if the user wants to expand their definition of word to beyond alphanumerics. They can use `iskeyword` locally to include whatever characters they want, e.g., `-`.)

**Comment by ratfactor** [comment]
@ds26gte Wow, not sure how I missed the notification for this. Thank you for submitting this issue!

You're absolutely right and I'll be submitting a fix shortly.

**Comment by ratfactor** [comment]
Fixed!

        Before: (cheese) -> link:(cheese)[(cheese)]
        After:  (cheese) -> (link:cheese[cheese])

Thanks again.
