### ISSUE TITLE
existing links problem

### ISSUE THREAD

**Issue by boydkelly** [ratfactor/vviki#5]
Hi,  First thanks for all this work!  

I don't know if there is an easy solution here.   I have a bunch of adocs that I want to navagate, and incorporate to a (hopefully) vviki.   The issue is the current links have the .adoc extension in them, ie:  link:new.adoc[New] 
If I click on those links, vvicki doesn't recognize it as a current link and creates "new.adoc.adoc".   If I set the g:vviki_ext="", then I can open existing links, but if I create new files they effectively have no extension...  :(   I have dozens of files and they are accessed elsewhere do I don't have the option of changing those links.

Note:  What do you think about https://github.com/samgriesemer/vim-roam?

**Comment by ratfactor** [comment]
@boydkelly Well, you sure caught me at the right time! I'm adding some new features right now and this is a really good fit.  I'm sure you won't be the only person wants this feature.  I'm going to add a new setting called `g:vviki_links_include_ext` which should do what you need.

No promises, but I expect to be releasing a v1.1 with this and other features within days.

I have stumbled upon *vim-roam* once before (and Roam Research as well) because I really enjoy reading about note-taking tools. I'm afraid I did not understand the advantages from reading the project README. Are there big advantages in the editing ergonomics, the external tooling, or something else?

**Comment by boydkelly** [comment]
Awesome!   Actually I did also notice the wiki.vim has a setting for adoc links, but it uses the "`adoc`  Asciidoc inter-page cross reference style links (|wiki-link-adoc|)"  which also doesn't help me, but could prove to be interesting for listing pages with those types of references.  (Disclaimer: I entered an issue with wiki.vim as well)
I looked briefly at vim-roam since apparently it works with vim.wiki, but I didn't even see exacly what it does, and I don't have vim wiki installed as it won't help me with adocs...
Yes I have also looked into obsidian and Zettlr to get more of a handle on classifying stuff.   I preferred Zettler, but neither have any support for adoc.  They won't even read them!   So they are out of the question, and the bottom line is I like simplicity as well.   Just this am I got some scripts working with ripgrep and fzf, that in a way enable any word on the fly to be a tag.   Works fast like lightning, and previews content in files where a word is found.  Anyway looking forward to your link solution and then at least I have a wiki too!

**Comment by ratfactor** [comment]
@boydkelly It sounds like we have the same philosophy regarding tooling! I'm also a fan of ripgrep (and The Silver Searcher) and FZF - they come together to make wonderfully fast, powerful, light custom tools.  I also have an endless fascination with zettelkasten-style note systems.

Good news on the link front: I just got the `g:vviki_links_include_ext` option working. I just need to document it and test all three new features (also alternative syntax for links, and visual selection for multi-word links) and then I can make the new feature version release.

**Comment by ratfactor** [comment]
@boydkelly The file extension link option is now live!

From the release 1.1.0 help documentation:

```
g:vviki_links_include_ext                            *vviki_links_include_ext*

By default, VViki creates wiki document links without file extensions. With
this option turned on, the file extension (see |vviki_ext|) will be included
in the link path (e.g. `link:foo[My Foo]` becomes `link:foo.adoc[My Foo]`).

Note that the two styles are incompatible - links created with the option on
will not work when the option is off and vice versa.

This option is off by default. Turn it on like so:
>
    let g:vviki_links_include_ext = 1
<
```

**Comment by boydkelly** [comment]
Thank you!   Awesome!
